### ISSUE TITLE
WrapText logic

### ISSUE THREAD

**Issue by BartVanHoutte-ADING** [ading-be/MTX.Conversion.ZebraWrap#3]
Device label data into number of lines as defined in configuration:
- GoTo character 20 (number of characters per line comes from configuration).
- Search back to the first character on which can be split (see analysis)
- Split text there and give it a specific line id => 190,30 will be 190,30,1 and 190,30,2, etc ...
- Repeat until the last line
- Remainder goes into the last line

**Comment by HavermansStef** [comment]
Almost fixed. Some small changes left to make to optimize the code.
